// levelcheck: validates level files and ranks them by difficulty. See docs/levels.md.
//   levelcheck [--map] [--quiet] [--script DIR] FILE...
// --script DIR writes DIR/<level name>.txt per valid level: a scenario (docs/testing.md) that plays the path the
// check found in the real game, in god mode, and expects the level to be finished at the end.
// Exit code: 0 all valid, 1 at least one level cannot be finished, 2 usage / unreadable file.

#include "../../src/world/level.h"
#include "../../src/world/level_check.h"
#include <algorithm>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace {
struct Entry {
	std::string path;
	LevelGrid grid;
	LevelReport report;
};

constexpr float GRIP = 0.45f;	  // where in a cell the player stands to climb (Dungeon LADDER_GRIP_X)
constexpr float GATE_STOP = 0.4f; // this close to a closed gate, a held key opens it (GATE_APPROACH is 0.45)
constexpr float CLIMB_MARGIN = 0.03f;

// Scenario commands for the path: walks are merged until something else has to happen.
class PathScript {
  public:
	PathScript(const LevelGrid& grid, const std::string& levelPath, float startX) : grid(grid), x(startX) {
		out = "# Generated by levelcheck --script: plays the path levelcheck found (god mode).\n";
		out += "seed 1\ngod\nlevel " + levelPath + "\nwait 30\n";
	}

	std::string build(const LevelReport& r) {
		for (size_t i = 1; i < r.path.size(); i++) {
			const CellPos& cur = r.path[i];
			float target = static_cast<float>(cur.col) + GRIP;
			switch (r.pathMoves[i]) {
			case PathMove::Walk:
				if (grid.at(cur.col, cur.row).a == Gate && grid.at(cur.col, cur.row).c == 0) {
					float dir = target > x ? 1.f : -1.f;
					walkTo(static_cast<float>(cur.col) + (dir > 0 ? -GATE_STOP : 1.f + GATE_STOP));
					line("wait 1400ms");
				}
				walkTo(target);
				break;
			case PathMove::Drop:
				walkTo(target);
				line("wait 1500ms");
				break;
			case PathMove::Climb:
				flushWalk();
				climb(cur.row > r.path[i - 1].row ? 1 : -1);
				break;
			case PathMove::Jump:
				flushWalk();
				line("jump");
				walkTo(target);
				flushWalk();
				line("wait 500ms");
				break;
			case PathMove::Pull:
				flushWalk();
				line("interact");
				line("wait 1400ms");
				break;
			case PathMove::Start:
				break;
			}
		}
		flushWalk();
		line("dump");
		line("interact");
		line("wait 5");
		line(r.finale ? "expect won == 1" : "expect level == 2");
		return out;
	}

  private:
	const LevelGrid& grid;
	float x;
	std::string out;
	float walkDir = 0.f;
	float walkLeft = 0.f;
	int climbDir = 0;
	int climbRows = 0;

	void line(const std::string& text) {
		flushWalk();
		flushClimb();
		out += text + "\n";
	}

	void walkTo(float target) {
		flushClimb();
		float dir = target > x ? 1.f : -1.f;
		if (std::fabs(target - x) < 0.001f)
			return;
		if (walkDir != 0.f && dir != walkDir)
			flushWalk();
		walkDir = dir;
		walkLeft += std::fabs(target - x);
		x = target;
	}

	void flushWalk() {
		if (walkDir == 0.f)
			return;
		char buf[64];
		snprintf(buf, sizeof(buf), "walk %s %.3f\n", walkDir > 0 ? "right" : "left", static_cast<double>(walkLeft));
		out += buf;
		walkDir = 0.f;
		walkLeft = 0.f;
	}

	void climb(int dir) {
		if (climbDir != 0 && dir != climbDir)
			flushClimb();
		climbDir = dir;
		climbRows++;
	}

	void flushClimb() {
		if (climbDir == 0)
			return;
		// Up a little past the row, down a little short of it: the player must end inside the target row, and
		// walking down onto the exact row edge would round into the cell below.
		char buf[64];
		snprintf(buf, sizeof(buf), "walk %s %.2f\n", climbDir > 0 ? "up" : "down",
				 static_cast<double>(climbRows) + (climbDir > 0 ? CLIMB_MARGIN : -CLIMB_MARGIN));
		out += buf;
		climbDir = 0;
		climbRows = 0;
	}
};

void printReport(const Entry& e, bool map) {
	const LevelReport& r = e.report;
	printf("== %s: %s\n", e.path.c_str(), r.valid ? "OK" : "INVALID");
	for (const std::string& m : r.errors)
		printf("   error: %s\n", m.c_str());
	for (const std::string& m : r.warnings)
		printf("   warning: %s\n", m.c_str());
	printf("   start (col %d, row %d), %s\n", r.start.col, r.start.row,
		   r.finale ? "goal: ankh (finale)" : "goal: exit");
	printf("   size: %d open cells, %d reachable, bounds %dx%d\n", r.openCells, r.reachableCells, r.boundsWidth,
		   r.boundsHeight);
	printf("   content: %d monsters (scarab %d, worm %d, plant %d, anubis %d, rat %d, giant rat %d), %d spikes, "
		   "%d death traps, %d rock falls, %d treasures (%d reachable), %d keys, %d gates, %d levers, %d riddles\n",
		   r.monsterCount, r.monsters[MonsterScarab], r.monsters[MonsterWorm], r.monsters[MonsterPlant],
		   r.monsters[MonsterAnubis], r.monsters[MonsterRat], r.monsters[MonsterGiantRat], r.spikes, r.deathTraps,
		   r.rockFalls, r.treasures, r.reachableTreasures, r.keys, r.gates, r.levers, r.riddles);
	if (r.valid || !r.path.empty())
		printf("   path: %d moves, %d jumps, %d drops, %d ladder steps, %d spikes, %d death traps, %d rock falls, "
			   "%d gates (%d colours), %d monsters near\n",
			   r.pathLength, r.pathJumps, r.pathDrops, r.pathClimb, r.pathSpikes, r.pathDeathTraps, r.pathRockFalls,
			   r.pathGates, r.keysNeeded, r.pathMonsters);
	printf("   difficulty: %.1f\n", r.difficulty);
	if (map)
		printf("%s", renderLevel(e.grid, &r).c_str());
}
} // namespace

int main(int argc, char** argv) {
	bool map = false;
	bool quiet = false;
	std::string scriptDir;
	std::vector<Entry> entries;
	int code = 0;
	for (int i = 1; i < argc; i++) {
		if (strcmp(argv[i], "--map") == 0) {
			map = true;
			continue;
		}
		if (strcmp(argv[i], "--quiet") == 0) {
			quiet = true;
			continue;
		}
		if (strcmp(argv[i], "--script") == 0 && i + 1 < argc) {
			scriptDir = argv[++i];
			continue;
		}
		if (argv[i][0] == '-') {
			fprintf(stderr, "usage: levelcheck [--map] [--quiet] [--script DIR] FILE...\n");
			return 2;
		}
		Entry e;
		e.path = argv[i];
		std::string error = loadLevelFile(argv[i], e.grid);
		if (!error.empty()) {
			fprintf(stderr, "%s: %s\n", argv[i], error.c_str());
			code = 2;
			continue;
		}
		e.report = checkLevel(e.grid);
		entries.push_back(std::move(e));
	}
	if (entries.empty() && code == 0) {
		fprintf(stderr, "usage: levelcheck [--map] [--quiet] [--script DIR] FILE...\n");
		return 2;
	}

	for (const Entry& e : entries) {
		if (!quiet)
			printReport(e, map);
		if (!e.report.valid && code == 0)
			code = 1;
		if (!scriptDir.empty() && e.report.valid) {
			std::string name = std::filesystem::path(e.path).filename().string();
			std::string file = (std::filesystem::path(scriptDir) / (name + ".txt")).string();
			std::ofstream script(file);
			// The game starts on the entrance cell's left edge (Dungeon::Load).
			script << PathScript(e.grid, e.path, static_cast<float>(e.report.start.col)).build(e.report);
			if (!quiet)
				printf("   script: %s\n", file.c_str());
		}
	}

	// Ranking, easiest first. The finale stays last whatever its score.
	std::vector<const Entry*> order;
	order.reserve(entries.size());
	for (const Entry& e : entries)
		order.push_back(&e);
	std::stable_sort(order.begin(), order.end(), [](const Entry* a, const Entry* b) {
		if (a->report.finale != b->report.finale)
			return b->report.finale;
		return a->report.difficulty < b->report.difficulty;
	});
	printf("\n%-4s %-28s %-7s %6s %5s %5s %8s %6s  %s\n", "rank", "level", "valid", "diff", "path", "reach", "monsters",
		   "traps", "notes");
	int rank = 1;
	for (const Entry* e : order) {
		const LevelReport& r = e->report;
		std::string notes;
		if (r.finale)
			notes += "finale ";
		if (!r.warnings.empty())
			notes += std::to_string(r.warnings.size()) + " warning(s) ";
		if (!r.errors.empty())
			notes += r.errors.front();
		printf("%-4d %-28s %-7s %6.1f %5d %5d %8d %6d  %s\n", rank++, e->path.c_str(), r.valid ? "yes" : "NO",
			   r.difficulty, r.pathLength, r.reachableCells, r.monsterCount, r.spikes + r.deathTraps + r.rockFalls,
			   notes.c_str());
	}
	return code;
}
