#!/bin/bash

CXXFLAGS="-Wall -Wextra -pedantic -O3 -march=native -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -MMD -MP"
LDFLAGS="-lX11  -lglut -lGL -lGLU -lm -ldl -L/usr/X11R6/lib -lSDL_mixer  -lSDL"

rm editor
g++ editor.c $CXXFLAGS -o  editor $LDFLAGS
#gcc game.c -Wall -pedantic -o  play.exe  -lX11 -lXi -lXmu -lglut -lGL -lGLU -lm -ldl -L/usr/X11R6/lib -lXxf86vm