#ifndef DECOR_H
#define DECOR_H

#include <cstdint>

// Static props and wall decals scattered on empty floor cells when a level loads (see Dungeon::scatterDecorations).
// Models and textures: Models/decorations/decor_<name>.md3, Textures/decorations/decor_<name>.png, built by
// tools/blender/models/decor.py in tile units (origin = floor centre of the tile on the back wall).
constexpr int DECOR_COUNT = 10;
constexpr int DECOR_WEB = 0; // modelled in the upper left corner, needs a ceiling
constexpr int DECOR_BRAZIER = 6;
constexpr int DECOR_LAMP = 7;
constexpr const char* DECOR_NAMES[DECOR_COUNT] = {"web",	  "pottery", "canopic", "rubble",  "sand",
												  "skeleton", "brazier", "lamp",	"scrolls", "ushabti"};

// The wall torch (Models/decorations/decor_torch.md3, also built by decor.py) is not in this list:
// Dungeon::scatterTorches places it on its own.

// Ladder pieces: one model per Ladder cell, Models/ladders/ladder_<style>_<piece>.md3 +
// Textures/ladders/ladder_<style>_<piece>.png, built by tools/blender/models/ladder.py in the same tile units as
// the props. Pieces stack seamlessly in any order; Dungeon::scatterLadders picks one style per shaft and a piece
// per cell.
constexpr int LADDER_STYLE_COUNT = 2;
constexpr int LADDER_MID_COUNT = 3; // interchangeable middle pieces, indices 0..2
constexpr int LADDER_TOP = 3;		// highest cell of the shaft
constexpr int LADDER_BOTTOM = 4;	// standing on the floor
constexpr int LADDER_PIECE_COUNT = 5;
constexpr const char* LADDER_STYLE_NAMES[LADDER_STYLE_COUNT] = {"wood", "vine"};
constexpr const char* LADDER_PIECE_NAMES[LADDER_PIECE_COUNT] = {"a", "b", "c", "top", "bottom"};
// Mirrored lianas would kink at the seams (their twist turns the other way), wooden pieces are symmetric enough.
constexpr bool LADDER_MIRRORS[LADDER_STYLE_COUNT] = {true, false};

struct LadderCell {
	int8_t style = -1; // -1 = no ladder, else index into LADDER_STYLE_NAMES
	int8_t piece = 0;  // index into LADDER_PIECE_NAMES
	bool mirror = false;
};

struct DecorCell {
	int8_t type = -1; // -1 = none, else index into DECOR_NAMES
	bool mirror = false;
	float offsetX = 0.f; // tile units
};

// Wall decals: quads on the back wall textured from the Textures/decorations/decals.png atlas (4 x 4 cells),
// generated by tools/textures/decals.py in this order.
enum class DecalAnchor : int8_t {
	Free,	 // anywhere on the wall
	Ceiling, // hangs from the ceiling, needs a wall above
	Floor,	 // grows from the floor, needs a wall below
};

struct DecalDef {
	DecalAnchor anchor;
	float size; // quad side, tile units
};

constexpr int DECAL_ATLAS_GRID = 4;
constexpr int DECAL_COUNT = 16;
constexpr DecalDef DECAL_DEFS[DECAL_COUNT] = {
	{DecalAnchor::Free, 0.6f},	   // crack
	{DecalAnchor::Free, 0.55f},	   // impact crack
	{DecalAnchor::Floor, 0.7f},	   // crack rising from the floor
	{DecalAnchor::Ceiling, 0.8f},  // hanging vines
	{DecalAnchor::Ceiling, 0.7f},  // flowering vines
	{DecalAnchor::Ceiling, 0.75f}, // roots
	{DecalAnchor::Ceiling, 0.85f}, // damp seepage with moss
	{DecalAnchor::Free, 0.75f},	   // hieroglyph column
	{DecalAnchor::Free, 0.8f},	   // hieroglyph row
	{DecalAnchor::Free, 0.6f},	   // cartouche
	{DecalAnchor::Free, 0.5f},	   // eye of Horus
	{DecalAnchor::Free, 0.75f},	   // winged sun
	{DecalAnchor::Floor, 0.7f},	   // papyrus
	{DecalAnchor::Floor, 0.45f},   // dry grass
	{DecalAnchor::Floor, 0.75f},   // creeper
	{DecalAnchor::Free, 0.5f},	   // moss
};

struct DecalCell {
	int8_t type = -1; // -1 = none, else index into DECAL_DEFS
	bool mirror = false;
	float x = 0.f, y = 0.f; // quad centre on the back wall, tile units
};

#endif
