#ifndef DECOR_H
#define DECOR_H

#include <cstdint>

// Static props and wall decals scattered on empty floor cells when a level loads (see Dungeon::scatterDecorations).
// Models and textures: models/decorations/decor_<name>.md3, textures/decorations/decor_<name>.png, built by
// tools/blender/models/decor.py in tile units (origin = floor centre of the tile on the back wall).
constexpr int DECOR_COUNT = 19;
constexpr int DECOR_SCATTERED = 18; // the first ones; the rest are placed on purpose
constexpr int DECOR_WEB = 0;		// modelled in the upper left corner, needs a ceiling
constexpr int DECOR_BRAZIER = 6;
constexpr int DECOR_LAMP = 7;
// Thoth's four statues: one pick among the props, then a variant at even odds (Dungeon::scatterDecorations). The
// crowns reach up to a wall torch.
constexpr int DECOR_THOTH = 13;
constexpr int DECOR_THOTH_VARIANTS = 4;
constexpr bool isThoth(int decor) { return decor >= DECOR_THOTH && decor < DECOR_THOTH + DECOR_THOTH_VARIANTS; }
constexpr int DECOR_COFFIN = 18; // empty, on every mummy's spawn tile: it lies in there until it wakes
constexpr const char* DECOR_NAMES[DECOR_COUNT] = {"web",
												  "pottery",
												  "canopic",
												  "rubble",
												  "sand",
												  "skeleton",
												  "brazier",
												  "lamp",
												  "scrolls",
												  "ushabti",
												  "cat",
												  "jackal",
												  "osiris",
												  "thoth_ibis_standing",
												  "thoth_ibis_seated",
												  "thoth_baboon_seated",
												  "thoth_baboon_standing",
												  "sarcophagus",
												  "coffin"};

// Decorations by depth (docs/plan/decor-by-depth.md): the tiers add up, a level draws from every tier unlocked at its
// depth, the newest one counting double. The first levels are a natural cave, the deepest a painted temple. Depth is
// the campaign level; a generated level's comes from its difficulty (level_gen.h), any other level gets them all.
constexpr int DECOR_TIER_COUNT = 4;
constexpr int DECOR_TIER_FROM[DECOR_TIER_COUNT] = {1, 4, 8, 13}; // cave, worked tunnel, tomb, temple / necropolis
constexpr int DECOR_DEPTH_ALL = 1000;							 // a level outside the campaign
constexpr int decorTier(int depth) {
	int tier = 0;
	while (tier + 1 < DECOR_TIER_COUNT && depth >= DECOR_TIER_FROM[tier + 1])
		tier++;
	return tier;
}
// The tier each prop comes in with; the coffin (-1) stands wherever a mummy lies.
constexpr int8_t DECOR_TIERS[DECOR_COUNT] = {0, 0, 1, 0, 0, 0, // web, pottery, canopic, rubble, sand, skeleton
											 1, 1, 1, 2, 2, 3, // brazier, lamp, scrolls, ushabti, cat, jackal
											 3, 2, 2, 2, 2, 3, // osiris, Thoth x 4, sarcophagus
											 -1};
// Rows of rough rock (the rest dressed stone), and of the dressed stretches the painted ones, per tier, in percent:
// all cave at first, less and less deeper down.
constexpr uint32_t ROUGH_PERCENT[DECOR_TIER_COUNT] = {100, 55, 30, 15};
constexpr uint32_t PAINTED_PERCENT[DECOR_TIER_COUNT] = {0, 0, 40, 55};
constexpr int STAR_CEILING_TIER = 3; // painted stretches get the starry ceiling from here, slabs before
constexpr int CRACKED_FLOOR_TIER = 1;
constexpr int SLAB_FLOOR_TIER = 2;

// The wall torch (models/decorations/decor_torch.md3, also built by decor.py) is not in this list:
// Dungeon::scatterTorches places it on its own.

// Surfaces of the cells: textures/dungeon/<name>.png, generated by tools/textures/surfaces.py in this order.
// Any two variants of a kind tile side by side, except that a painted wall and a stone one meet through
// WALL_PLASTER_BROKEN (plaster on the left, stone on the right; mirrored for the other way round).
// Dungeon::scatterSurfaces picks one per cell.
constexpr int WALL_PLASTER = 0;
constexpr int WALL_PLASTER_WORN = 1;
constexpr int WALL_PLASTER_BROKEN = 2;
constexpr int WALL_STONE = 3;
constexpr int WALL_STONE_CRACKED = 4;
constexpr int WALL_STONE_SAND = 5;
constexpr int WALL_ROUGH = 6;
constexpr int WALL_ROUGH_STRATA = 7;
constexpr int WALL_STYLE_COUNT = 8;
constexpr const char* WALL_STYLE_NAMES[WALL_STYLE_COUNT] = {"wall_plaster", "wall_plaster_worn",  "wall_plaster_broken",
															"wall_stone",	"wall_stone_cracked", "wall_stone_sand",
															"wall_rough",	"wall_rough_strata"};

constexpr int FLOOR_SLABS = 0;
constexpr int FLOOR_SAND = 1;
constexpr int FLOOR_CRACKED = 2;
constexpr int FLOOR_STYLE_COUNT = 3;
constexpr const char* FLOOR_STYLE_NAMES[FLOOR_STYLE_COUNT] = {"floor_slabs", "floor_sand", "floor_cracked"};

constexpr int CEILING_STARS = 0; // over painted walls
constexpr int CEILING_SLABS = 1; // over stone walls
constexpr int CEILING_ROUGH = 2; // over rough walls
constexpr int CEILING_STYLE_COUNT = 3;
constexpr const char* CEILING_STYLE_NAMES[CEILING_STYLE_COUNT] = {"ceiling_stars", "ceiling_slabs", "ceiling_rough"};

// The face of a solid cell: textures/dungeon/rock.png, one image over 2 x 2 cells.
constexpr const char* ROCK_TEXTURE = "textures/dungeon/rock.png";

struct SurfaceCell {
	int wall = WALL_STONE; // back and side walls
	int floor = FLOOR_SLABS;
	int ceiling = CEILING_SLABS;
	bool wallMirror = false; // u flipped on the walls: stone on the left of WALL_PLASTER_BROKEN
};

// Ladder pieces: one model per Ladder cell, models/ladders/ladder_<style>_<piece>.md3 +
// textures/ladders/ladder_<style>_<piece>.png, built by tools/blender/models/ladder.py in the same tile units as
// the props. Pieces stack seamlessly in any order; Dungeon::scatterLadders picks one style per shaft and a piece
// per cell.
constexpr int LADDER_STYLE_COUNT = 2;
constexpr int LADDER_MID_COUNT = 3; // interchangeable middle pieces, indices 0..2
constexpr int LADDER_TOP = 3;		// highest cell of the shaft
constexpr int LADDER_BOTTOM = 4;	// standing on the floor
constexpr int LADDER_PIECE_COUNT = 5;
constexpr const char* LADDER_STYLE_NAMES[LADDER_STYLE_COUNT] = {"wood", "vine"};
constexpr const char* LADDER_PIECE_NAMES[LADDER_PIECE_COUNT] = {"a", "b", "c", "top", "bottom"};
// Mirrored lianas would kink at the seams (their twist turns the other way), wooden pieces are symmetric enough.
constexpr bool LADDER_MIRRORS[LADDER_STYLE_COUNT] = {true, false};

struct LadderCell {
	int8_t style = -1; // -1 = no ladder, else index into LADDER_STYLE_NAMES
	int8_t piece = 0;  // index into LADDER_PIECE_NAMES
	bool mirror = false;
};

struct DecorCell {
	int8_t type = -1; // -1 = none, else index into DECOR_NAMES
	bool mirror = false;
	float offsetX = 0.f; // tile units
};

// Wall decals: quads on the back wall textured from the textures/decorations/decals.png atlas (4 x 4 cells),
// generated by tools/textures/decals.py in this order.
enum class DecalAnchor : int8_t {
	Free,	 // anywhere on the wall
	Ceiling, // hangs from the ceiling, needs a wall above
	Floor,	 // grows from the floor, needs a wall below
};

struct DecalDef {
	DecalAnchor anchor;
	float size; // quad side, tile units
};

constexpr int DECAL_ATLAS_GRID = 4;
constexpr int DECAL_COUNT = 16;
constexpr DecalDef DECAL_DEFS[DECAL_COUNT] = {
	{DecalAnchor::Free, 0.6f},	   // crack
	{DecalAnchor::Free, 0.55f},	   // impact crack
	{DecalAnchor::Floor, 0.7f},	   // crack rising from the floor
	{DecalAnchor::Ceiling, 0.8f},  // hanging vines
	{DecalAnchor::Ceiling, 0.7f},  // flowering vines
	{DecalAnchor::Ceiling, 0.75f}, // roots
	{DecalAnchor::Ceiling, 0.85f}, // damp seepage with moss
	{DecalAnchor::Free, 0.75f},	   // hieroglyph column
	{DecalAnchor::Free, 0.8f},	   // hieroglyph row
	{DecalAnchor::Free, 0.6f},	   // cartouche
	{DecalAnchor::Free, 0.5f},	   // eye of Horus
	{DecalAnchor::Free, 0.75f},	   // winged sun
	{DecalAnchor::Floor, 0.7f},	   // papyrus
	{DecalAnchor::Floor, 0.45f},   // dry grass
	{DecalAnchor::Floor, 0.75f},   // creeper
	{DecalAnchor::Free, 0.5f},	   // moss
};
// The tier each decal comes in with (DECOR_TIERS): cracks and growth anywhere, the single eye of Horus in the worked
// tunnels, glyph columns, rows and cartouches in the tombs, the painted winged sun in the temples.
constexpr int8_t DECAL_TIERS[DECAL_COUNT] = {0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 3, 0, 0, 0, 0};

struct DecalCell {
	int8_t type = -1; // -1 = none, else index into DECAL_DEFS
	bool mirror = false;
	float x = 0.f, y = 0.f; // quad centre on the back wall, tile units
};

#endif
